### ISSUE TITLE
UnicodeDecodeError in the process of "Convert XML bug repository to a dictionary"

### ISSUE THREAD

**Issue by seanxiaoyan** [h4iku/bug-localization#3]
Hi, I encountered this error, do you know how to fix it?

Parsing & Preprocessing...
Traceback (most recent call last):
  File "buglocalizer/main.py", line 10, in <module>
d(), force_list=g.main(){'file', 'bug'})bug-localization/buglocalizer/preprocessing.py", line 399, in main

  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 13716: invalid start byte

**Comment by h4iku** [comment]
Hi
Could you tell me which dataset is this so I can reproduce the error?

**Comment by seanxiaoyan** [comment]
Thanks for the reply.
It happens for aspectj and zxing datasets
aspectj:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3121: invalid start byte
```

zxing:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 13716: invalid start byte
```

Also, for swt dataset, is it normal to get this warning?
```
UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
```

**Comment by h4iku** [comment]
Thanks for reporting the issue. I hadn't checked the code on Linux, and platform-dependent encoding differences were causing the problem. The code should be fixed now.

And yes, the warning is ok. Sometimes when the vectors only have out of vocabulary tokens, they become empty, and Spacy shows that warning.

**Comment by seanxiaoyan** [comment]
Thank you

**Comment by seanxiaoyan** [comment]
still getting error for aspectj dataset
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3121: invalid start byte

**Comment by h4iku** [comment]
I guess I need to specify the encoding for source files as well.
Should be fixed.
